### ISSUE TITLE
Python SDK: ModuleNotFoundError: No module named 'infisical_py'

### ISSUE THREAD

**Issue by alexander-schillemans** [Infisical/sdk#10]
When trying to use this new SDK, as per the official documentation, I'm getting this error.
Upon inspecting the installed package I see that there seems to be missing files inside the root directory.
Is this a known issue? Should I migrate back to the old package?

**Comment by DanielHougaard** [comment]
Hi Alexander, that sounds unusual! I'll need a bit of information from your environment to be able to debug this on my end.

- What Python version are you using?
- What operating system are you getting the error on? (Windows x64/x32, MacOS arm64/x86, etc)
- The full error you're getting in your terminal

And thanks for reporting!

**Comment by DanielHougaard** [comment]
@alexander-schillemans I was able to debug the issue on my end, and I just released a new version where this is fixed. Please download >=1.2.0, and thank you again for reporting this!
