### ISSUE TITLE
add .whl file to PyPI

### ISSUE THREAD

**Issue by l0ll0-21** [Infisical/sdk#16]
Could you provide a .whl file for the infisical_python package?
I have so installation issues with the tar.gz that you provide....
I takes forever and at the end i get an error. 

I tried different versions (2.0.5, 2.0.3)  and different Python versions (3.9/3.11)

I really would try out your stuff....

  Using cached infisical_python-2.0.6.tar.gz (39 kB)
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'error'
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001B88A26D150>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/maturin/
      WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001B88A2C7090>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/maturin/
      WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001B88DA8CFD0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/maturin/
      WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001B88DA8DE90>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/maturin/
      WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001B88DA8E550>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/maturin/
      ERROR: Could not find a version that satisfies the requirement maturin<0.15,>=0.14 (from versions: none)
      ERROR: No matching distribution found for maturin<0.15,>=0.14
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

**Comment by DanielHougaard** [comment]
Hi @l0ll0-21, that doesn't sound right. Which OS are you on? Please specify the specific architecture if possible, thanks!

**Comment by l0ll0-21** [comment]
Hi, I´m on Win10, 64bit x86

**Comment by DanielHougaard** [comment]
Hi @l0ll0-21, sorry for the delayed reply. This issues seems to refer to a connection issue to PyPI rather than an issue with the SDK. Could I have you try on a different internet connection, or perhaps with a VPN enabled? Thanks!

**Comment by DanielHougaard** [comment]
Hi @l0ll0-21! I have just released a new version _(2.1.8)_ which addresses this. Could I please have you give it a try? Thanks!

**Comment by l0ll0-21** [comment]
thanks @DanielHougaard. Worked like a charm.
