### ISSUE TITLE
Python/SDK: Critical errors with pyo3

### ISSUE THREAD

**Issue by gaby** [Infisical/sdk#27]
I have notice that when a server is running for +1 day using the infisical sdk errors will start showing up from pyo3 complaining about "No file handlers available". The only way to fix this is to restart the container running the python server.

This issue didn't happen with https://github.com/Infisical/infisical-python

Example Code (Throws error):
```python
import time
from infisical_client import InfisicalClient, EncryptSymmetricOptions, DecryptSymmetricOptions

while True:
    #client = InfisicalClient()
    key = InfisicalClient().createSymmetricKey()
    encryptOptions = EncryptSymmetricOptions(
        key=key,
        plaintext="Infisical is awesome!"
    )

    encryptedData = InfisicalClient().encryptSymmetric(encryptOptions)

    decryptOptions = DecryptSymmetricOptions(
        ciphertext=encryptedData.ciphertext,
        iv=encryptedData.iv,
        tag=encryptedData.tag,
        key=key
    )

    decryptedString = InfisicalClient().decryptSymmetric(decryptOptions)
    print(f"Key={key}, cipher={decryptedString}")
```

Example Code (Works as intended):

```python
import time
from infisical_client import InfisicalClient, EncryptSymmetricOptions, DecryptSymmetricOptions

while True:
    client = InfisicalClient()
    key = client.createSymmetricKey()
    encryptOptions = EncryptSymmetricOptions(
        key=key,
        plaintext="Infisical is awesome!"
    )

    encryptedData = client.encryptSymmetric(encryptOptions)

    decryptOptions = DecryptSymmetricOptions(
        ciphertext=encryptedData.ciphertext,
        iv=encryptedData.iv,
        tag=encryptedData.tag,
        key=key
    )

    decryptedString = client.decryptSymmetric(decryptOptions)
    print(f"Key={key}, cipher={decryptedString}")
```

@DanielHougaard Any ideas?

**Comment by DanielHougaard** [comment]
Hi @gaby, sorry for the delayed response. Are you able to share a stack trace or a more complete error?

**Comment by DanielHougaard** [comment]
That's interesting, thank you for the stack traces. I'm leaning towards it being a cleanup issue. The Python garbage collector should be freeing up the resources being used by the client at the end of the loop, but it appears that something is going wrong there.
I'll need to look deeper into this before I can give you a detailed rundown of what's going wrong. I'll keep you in the loop!

Thank you for reporting this, @gaby

**Comment by gaby** [comment]
@DanielHougaard Any update on this? I notice it still happens randomly using the "Working Example" above in tbe latest SDK version.

I'm not sure if its a bug in pyo3_runtime or the way the SDK is using it.

**Comment by gaby** [comment]
@DanielHougaard Asking ChatGPT I found two issues. First one is there's no limits being set for tokio threads:

```rust
use tokio::runtime::Builder;

#[tokio::main(flavor = "multi_thread", worker_threads = 4)] // Adjust the number of worker threads as needed
async fn main() {
    // Your code here
}
```

Second issue is the Rust code is using async with pyo3 and it should be using `pyo3-asyncio` https://github.com/awestlake87/pyo3-asyncio

Example
```rust
#[pymethods]
impl InfisicalClient {
    #[pyo3(text_signature = "($self, command_input)")]
    fn run_command<'a>(&'a mut self, command_input: String) -> PyResult<&'a PyAny> {
        Python::with_gil(|py| {
            future_into_py(py, async move {
                match run_command(&mut self.client, &command_input).await {
                    Ok(result) => Ok(result),
                    Err(e) => Err(pyo3::exceptions::PyRuntimeError::new_err(format!("{:?}", e))),
                }
            })
        })
    }
}

async fn run_command(client: &mut JsonClient, input_str: &str) -> Result<String, Box<dyn std::error::Error>> {
    client.run_command(input_str).await
}
```

**Comment by gaby** [comment]
I have moved on to use something else. This library can't handle high concurrency or be used from an HTTP handler.

**Comment by gaby** [comment]
Just an FYI, because of this issue we had to completely move off `Infisical`.

**Comment by DanielHougaard** [comment]
HI @gaby, apologies for the delayed response here.

We have recently rolled out a native Python SDK (https://github.com/Infisical/python-sdk-official), which should resolve this issue. The new SDK is not dependent on Rust at all, and will run just like any Python library.

**Comment by gaby** [comment]
@DanielHougaard Thanks, any plans to re-add the encryption utils to it ?

**Comment by DanielHougaard** [comment]
Hey @gaby, you're right that those are currently missing from the new SDK. Let me re-add them for you!

**Comment by DanielHougaard** [comment]
Hi @gaby, after talking with the team about it, we've decided to not add the cryptography methods to the new native SDK. The reason for this, is because it's not proprietary or strictly related to Infisical, and the same can be achieved by using an external package which handles encryption.

Instead, we're going to be adding the Infisical KMS into our SDK! However a deadline for this hasn't been set yet, but it's on our roadmap for the Python SDK.

**Comment by gaby** [comment]
@DanielHougaard Sounds good, I will keep track of the releases.
