### ISSUE TITLE
getSecret with 'path' argument returns cached value for different path

### ISSUE THREAD

**Issue by db-hui** [Infisical/sdk#29]
Steps to reproduce:

* create a project with two folders `/path_1` and `/path_2`
* add `MY_SECRET `to both folders, but give them different values `value_1` and `value_2`
* run `getSecret `while specifying `/path_1` in the first call and` /path_2` in the second call

`getSecret` yields the same value for both calls, sometimes `value_1`, sometimes `value_2`.

`listSecrets` lists correct values when specifying `path`.

My assumption is that keys with similar names but different values should be able to exist in different folders (paths)?

It looks like Infisical's internal cache is not taking `path` into account?

Please let me know if you need any additional info.

**Comment by DanielHougaard** [comment]
Hi @db-hui, apologies for the delay. I'm looking into this issue now!

**Comment by DanielHougaard** [comment]
Hi @db-hui. This is now resolved in version `2.2.3` and later. Thank you for reporting this!
