### ISSUE TITLE
GoLang SDK

### ISSUE THREAD

**Issue by chaddyc** [Infisical/sdk#30]
GoLang developers would want to make use of this feature. Many backend and microservices are being built by companies and organizations so it is worthwhile building a GoLang SDK.

**Comment by craigtracey** [comment]
I will second this request! 

I have had a lot of success generating OpenAPI clients with `oapi-codegen`, but there are some Infisical API semantics that cause generation to fail. Some simple, non-impactful changes to the spec might allow for new client bindings to be generated easily...for Go and other languages as well.

Unfortunately, without Go bindings we will not be able to use Infisical :(

**Comment by DanielHougaard** [comment]
Hi @chaddyc @craigtracey. This is now on the roadmap for the coming week!

**Comment by DanielHougaard** [comment]
Hi @chaddyc, @sagikazarmark, @gaby, and @juneeighteen, We have just released a native Go Lang SDK!

Repository: https://github.com/Infisical/go-sdk
Documentation: https://infisical.com/docs/sdks/languages/go

**Comment by gaby** [comment]
@DanielHougaard Thank you! Looking forward to trying it out. Are the plans to add the Crypto utils to the Go SDK ?

Example: https://gist.github.com/donvito/efb2c643b724cf6ff453da84985281f8
