### ISSUE TITLE
Node @infisical/sdk is not working with nodemon

### ISSUE THREAD

**Issue by edishu** [Infisical/sdk#31]
My code:

```ts
import { InfisicalClient, LogLevel } from "@infisical/sdk";

// Secret
const client = new InfisicalClient({
  clientId: "YOUR_CLIENT_ID",
  clientSecret: "YOUR_CLIENT_SECRET",
  logLevel: LogLevel.Error,
});
```

When I start this app with `nodemon` and `ts-node`. I get following error:

```ts
[nodemon] 3.1.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node -T src/index.ts`
  logLevel: LogLevel.Error,
```

**Comment by DanielHougaard** [comment]
@edishu I don't see any errors in your snippets. Can you please elaborate?

**Comment by DanielHougaard** [comment]
@edishu There seems to be an issue with the LogLevel import. Please remove the `logLevel` line from the InfisicalClient constructor, and remove the import from the first line. 

We're looking into a proper fix for this!
