### ISSUE TITLE
Bring back the cryptography functions for Python SDK

### ISSUE THREAD

**Issue by gaby** [Infisical/sdk#4]
I just noticed the deprecation noticed in the Python SDK. While I look forward to migrating to this package, one major downside is the removal of the Crytography functions.

These functions made using infisical more practical since we could encrypt data before storing it in infisical.

Could these funtion be added to this repo?

https://github.com/Infisical/infisical-python?tab=readme-ov-file#cryptography

**Comment by DanielHougaard** [comment]
Hey Gaby! Thanks for the suggestion. We decided to not include it in the first iteration, but we will defiantly add this as soon as possible considering your suggestion. I'll post an update once a PR is ready!

**Comment by gaby** [comment]
@DanielHougaard Thanks! Looking forward

**Comment by DanielHougaard** [comment]
@gaby A PR is now open!

**Comment by gaby** [comment]
@DanielHougaard Nice! Looking forward to migrating to this sdk once that gets merge. Thanks!

**Comment by DanielHougaard** [comment]
@gaby This functionality is now live!
SDK version 1.1.3 has encryption support 👌

**Comment by gaby** [comment]
@DanielHougaard Thank you for the quick turn around! 💪
