### ISSUE TITLE
.NET SDK: `ExpandSecretReferences` option is not working

### ISSUE THREAD

**Issue by wtmzoo** [Infisical/sdk#50]
**Main issue:** `ExpandSecretReferences` option for `GetSecret` method is not working.

### Test environment

1. Database folder with DB_USER and DB_PASSWORD secrets;
2. DB_CONNECTION_STRING secret with interpolated string like: `${dev.DATABASE.DB_USER}:${dev.DATABASE.DB_PASSWORD}`

<img width="1245" alt="Screen1" src="https://github.com/user-attachments/assets/99ee626f-4fe8-4cda-a587-ac1fb666ca89">
<img width="1240" alt="screen2" src="https://github.com/user-attachments/assets/ebf650dd-3c3f-4ad9-a46a-d7a72bf09420">
<img width="1255" alt="db_folder" src="https://github.com/user-attachments/assets/3d087846-323f-4f46-9179-db1af65b9c00">

When I try to retrieve the DB_CONNECTION_STRING using the Infisical .NET SDK, I receive an unresolved string in response.

C# Code:
```csharp
var getDatabaseConStringOptions = new GetSecretOptions
{
    SecretName = "DB_CONNECTION_STRING",
    Path = "/",
    ProjectId = "xxxxxx",
    Environment = "dev",
    ExpandSecretReferences = true
};

var cfg = _client.GetSecret(getDatabaseConStringOptions);
```

Deserialized response:
<img width="745" alt="screen45" src="https://github.com/user-attachments/assets/f8875eaf-f8f7-483b-96a9-61809e0ea78d">

This may appear to be a bug in Infisical itself, but I additionally did some testing with Postman, which showed that Infisical responds to the correct query with the correct answer:

![image](https://github.com/user-attachments/assets/863ba0d2-b4a3-4af9-bc8a-b50c274a2500)

Looking forward to your response! Thank you!

**Comment by DanielHougaard** [comment]
Hello @wtmzoo, thank you for the report. I've just released a new version that resolves this issue. Please update to version `2.3.7`. Thank you!
