### ISSUE TITLE
Missing file `lib/extended_schemas/schemas.rb` 

### ISSUE THREAD

**Issue by san983** [Infisical/sdk#54]
Hi! It looks the Ruby Gem is missing a file therefore the gem is not loading

```
> docker run -it  --rm ruby:3.3-slim bash

root@aa6583b52dd6:/# gem update --system
Fetching rubygems-update-3.5.22.gem
Successfully installed rubygems-update-3.5.22
...

root@aa6583b52dd6:/# gem install infisical-sdk
...
Successfully installed infisical-sdk-2.3.7
20 gems installed

root@aa6583b52dd6:/# irb -r infisical-sdk
/usr/local/lib/ruby/3.3.0/irb/init.rb:436: warning: LoadError: cannot load such file -- /usr/local/bundle/gems/infisical-sdk-2.3.7/lib/extended_schemas/schemas
```

**Comment by DanielHougaard** [comment]
Hi @san983, thank you for the report. I'll take a look at this shortly!

**Comment by san983** [comment]
> Hi @san983, thank you for the report. I'll take a look at this shortly!

Thanks, let me know what can I help with.

**Comment by DanielHougaard** [comment]
Hi @san983, closing this issue as we've been in touch via. email. For anyone facing the same issue, please upgrade the SDK version.
